// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderProcessing.Models;

public partial class AuditLog
{
    public long AuditLogId { get; set; }

    public string EntityType { get; set; }

    public string EntityId { get; set; }

    public string ActionCode { get; set; }

    public long? UserId { get; set; }

    public string MetadataJson { get; set; }

    public DateTime OccurredAtUtc { get; set; }

    public virtual User User { get; set; }
}