// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderProcessing.Models;

public partial class Customer
{
    public long CustomerId { get; set; }

    public long? UserId { get; set; }

    public string DisplayName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string ExternalReference { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; } = new List<CustomerAddress>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual User User { get; set; }
}