// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderProcessing.Models;

public partial class CustomerAddress
{
    public long CustomerAddressId { get; set; }

    public long CustomerId { get; set; }

    public string Label { get; set; }

    public string RecipientName { get; set; }

    public string Phone { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string City { get; set; }

    public string StateOrRegion { get; set; }

    public string PostalCode { get; set; }

    public string CountryCode { get; set; }

    public bool IsDefault { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<OrderShippingSnapshot> OrderShippingSnapshots { get; set; } = new List<OrderShippingSnapshot>();
}