// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderProcessing.Models;

public partial class InventoryLedger
{
    public long InventoryLedgerId { get; set; }

    public long OrderId { get; set; }

    public long ProductId { get; set; }

    public string MovementType { get; set; }

    public int Quantity { get; set; }

    public string IdempotencyKey { get; set; }

    public bool Succeeded { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }
}