// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderProcessing.Models;

public partial class OrderStatusHistory
{
    public long OrderStatusHistoryId { get; set; }

    public long OrderId { get; set; }

    public string FromStatus { get; set; }

    public string ToStatus { get; set; }

    public string Reason { get; set; }

    public string ActorType { get; set; }

    public long? ActorUserId { get; set; }

    public Guid? CorrelationId { get; set; }

    public DateTime OccurredAtUtc { get; set; }

    public virtual User ActorUser { get; set; }

    public virtual Order Order { get; set; }
}