// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderProcessing.Models;

public partial class OrderProcessingJob
{
    public long JobId { get; set; }

    public long OrderId { get; set; }

    public string JobStatus { get; set; }

    public int Attempt { get; set; }

    public int RetryCount { get; set; }

    public int MaxRetries { get; set; }

    public DateTime? NextRetryAtUtc { get; set; }

    public DateTime? LockedAtUtc { get; set; }

    public Guid? LockToken { get; set; }

    public DateTime? LockExpiresAtUtc { get; set; }

    public string LastError { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<OrderDomainEvent> OrderDomainEvents { get; set; } = new List<OrderDomainEvent>();
}