// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderProcessing.Models;

public partial class OrderShippingSnapshot
{
    public long OrderId { get; set; }

    public string RecipientName { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string City { get; set; }

    public string StateOrRegion { get; set; }

    public string PostalCode { get; set; }

    public string CountryCode { get; set; }

    public string DeliveryInstructions { get; set; }

    public long? SourceCustomerAddressId { get; set; }

    public virtual Order Order { get; set; }

    public virtual CustomerAddress SourceCustomerAddress { get; set; }
}