// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderProcessing.Models;

public partial class Order
{
    public long OrderId { get; set; }

    public long CustomerId { get; set; }

    public string Status { get; set; }

    public decimal TotalAmount { get; set; }

    public string Currency { get; set; }

    public string IdempotencyKey { get; set; }

    public string FailureReason { get; set; }

    public Guid? CorrelationId { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public DateTime? CompletedAtUtc { get; set; }

    public DateTime? CancelledAtUtc { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<InventoryLedger> InventoryLedgers { get; set; } = new List<InventoryLedger>();

    public virtual ICollection<OrderDomainEvent> OrderDomainEvents { get; set; } = new List<OrderDomainEvent>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual OrderProcessingJob OrderProcessingJob { get; set; }

    public virtual OrderShippingSnapshot OrderShippingSnapshot { get; set; }

    public virtual ICollection<OrderStatusHistory> OrderStatusHistories { get; set; } = new List<OrderStatusHistory>();

    public virtual PaymentAttempt PaymentAttempt { get; set; }
}