// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderProcessing.Models;

public partial class OrderDomainEvent
{
    public long OrderDomainEventId { get; set; }

    public long OrderId { get; set; }

    public long? JobId { get; set; }

    public string EventType { get; set; }

    public string PayloadJson { get; set; }

    public string Severity { get; set; }

    public string ActorType { get; set; }

    public long? ActorUserId { get; set; }

    public Guid? CorrelationId { get; set; }

    public DateTime OccurredAtUtc { get; set; }

    public virtual User ActorUser { get; set; }

    public virtual OrderProcessingJob Job { get; set; }

    public virtual Order Order { get; set; }
}