// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace OrderProcessing.Models;

public partial class OrderProcessingContext : DbContext
{
    public OrderProcessingContext(DbContextOptions<OrderProcessingContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }

    public virtual DbSet<InventoryLedger> InventoryLedgers { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDomainEvent> OrderDomainEvents { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    public virtual DbSet<OrderProcessingJob> OrderProcessingJobs { get; set; }

    public virtual DbSet<OrderShippingSnapshot> OrderShippingSnapshots { get; set; }

    public virtual DbSet<OrderStatusHistory> OrderStatusHistories { get; set; }

    public virtual DbSet<PaymentAttempt> PaymentAttempts { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserLoginOtp> UserLoginOtps { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<UserSession> UserSessions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.ToTable("AuditLog");

            entity.HasIndex(e => new { e.EntityType, e.EntityId, e.OccurredAtUtc }, "IX_AuditLog_Entity").IsDescending(false, false, true);

            entity.Property(e => e.ActionCode)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.EntityId)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.EntityType)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.OccurredAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AuditLog_OccurredAtUtc");

            entity.HasOne(d => d.User).WithMany(p => p.AuditLogs)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_AuditLog_Users");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasIndex(e => e.UserId, "UQ_Customers_UserId").IsUnique();

            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Customers_CreatedAtUtc");
            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.ExternalReference).HasMaxLength(128);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Customers_IsActive");
            entity.Property(e => e.Phone).HasMaxLength(50);

            entity.HasOne(d => d.User).WithOne(p => p.Customer)
                .HasForeignKey<Customer>(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Customers_Users");
        });

        modelBuilder.Entity<CustomerAddress>(entity =>
        {
            entity.HasIndex(e => e.CustomerId, "IX_CustomerAddresses_CustomerId");

            entity.Property(e => e.AddressLine1)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.AddressLine2).HasMaxLength(256);
            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.CountryCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CustomerAddresses_CreatedAtUtc");
            entity.Property(e => e.IsDefault).HasAnnotation("Relational:DefaultConstraintName", "DF_CustomerAddresses_IsDefault");
            entity.Property(e => e.Label).HasMaxLength(64);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.PostalCode)
                .IsRequired()
                .HasMaxLength(32);
            entity.Property(e => e.RecipientName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.StateOrRegion).HasMaxLength(128);

            entity.HasOne(d => d.Customer).WithMany(p => p.CustomerAddresses)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_CustomerAddresses_Customers");
        });

        modelBuilder.Entity<InventoryLedger>(entity =>
        {
            entity.ToTable("InventoryLedger");

            entity.HasIndex(e => e.OrderId, "IX_InventoryLedger_OrderId");

            entity.HasIndex(e => e.IdempotencyKey, "UQ_InventoryLedger_IdempotencyKey").IsUnique();

            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_InventoryLedger_CreatedAtUtc");
            entity.Property(e => e.IdempotencyKey)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.MovementType)
                .IsRequired()
                .HasMaxLength(32);
            entity.Property(e => e.Succeeded)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_InventoryLedger_Succeeded");

            entity.HasOne(d => d.Order).WithMany(p => p.InventoryLedgers)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_InventoryLedger_Orders");

            entity.HasOne(d => d.Product).WithMany(p => p.InventoryLedgers)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InventoryLedger_Products");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasIndex(e => new { e.CustomerId, e.CreatedAtUtc }, "IX_Orders_CustomerId_CreatedAt").IsDescending(false, true);

            entity.HasIndex(e => new { e.Status, e.CreatedAtUtc }, "IX_Orders_Status_CreatedAt").IsDescending(false, true);

            entity.HasIndex(e => e.IdempotencyKey, "UQ_Orders_IdempotencyKey").IsUnique();

            entity.Property(e => e.CancelledAtUtc).HasPrecision(3);
            entity.Property(e => e.CompletedAtUtc).HasPrecision(3);
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Orders_CreatedAtUtc");
            entity.Property(e => e.Currency)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasDefaultValue("USD")
                .IsFixedLength()
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Orders_Currency");
            entity.Property(e => e.FailureReason).HasMaxLength(500);
            entity.Property(e => e.IdempotencyKey)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(32);
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Orders_UpdatedAtUtc");

            entity.HasOne(d => d.Customer).WithMany(p => p.Orders)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Orders_Customers");
        });

        modelBuilder.Entity<OrderDomainEvent>(entity =>
        {
            entity.HasIndex(e => new { e.EventType, e.OccurredAtUtc }, "IX_OrderDomainEvents_EventType");

            entity.HasIndex(e => new { e.OrderId, e.OccurredAtUtc }, "IX_OrderDomainEvents_Order_Time");

            entity.Property(e => e.ActorType)
                .IsRequired()
                .HasMaxLength(32);
            entity.Property(e => e.EventType)
                .IsRequired()
                .HasMaxLength(80);
            entity.Property(e => e.OccurredAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ODE_OccurredAtUtc");
            entity.Property(e => e.Severity)
                .IsRequired()
                .HasMaxLength(16)
                .HasDefaultValue("Info")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ODE_Severity");

            entity.HasOne(d => d.ActorUser).WithMany(p => p.OrderDomainEvents)
                .HasForeignKey(d => d.ActorUserId)
                .HasConstraintName("FK_OrderDomainEvents_ActorUser");

            entity.HasOne(d => d.Job).WithMany(p => p.OrderDomainEvents)
                .HasForeignKey(d => d.JobId)
                .HasConstraintName("FK_OrderDomainEvents_Jobs");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDomainEvents)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_OrderDomainEvents_Orders");
        });

        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.HasIndex(e => e.ProductId, "IX_OrderItems_ProductId");

            entity.HasIndex(e => new { e.OrderId, e.ProductId }, "UQ_OrderItems_Order_Product").IsUnique();

            entity.Property(e => e.LineTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_OrderItems_Orders");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItems_Products");
        });

        modelBuilder.Entity<OrderProcessingJob>(entity =>
        {
            entity.HasKey(e => e.JobId);

            entity.HasIndex(e => new { e.JobStatus, e.NextRetryAtUtc, e.CreatedAtUtc }, "IX_OPJ_PickQueue").HasFilter("([JobStatus] IN (N'Pending', N'InProgress'))");

            entity.HasIndex(e => e.OrderId, "UX_OPJ_OneActivePerOrder")
                .IsUnique()
                .HasFilter("([JobStatus] IN (N'Pending', N'InProgress'))");

            entity.Property(e => e.Attempt).HasAnnotation("Relational:DefaultConstraintName", "DF_OPJ_Attempt");
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_OPJ_CreatedAtUtc");
            entity.Property(e => e.JobStatus)
                .IsRequired()
                .HasMaxLength(32);
            entity.Property(e => e.LastError).HasMaxLength(2000);
            entity.Property(e => e.LockExpiresAtUtc).HasPrecision(3);
            entity.Property(e => e.LockedAtUtc).HasPrecision(3);
            entity.Property(e => e.MaxRetries)
                .HasDefaultValue(5)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_OPJ_MaxRetries");
            entity.Property(e => e.NextRetryAtUtc).HasPrecision(3);
            entity.Property(e => e.RetryCount).HasAnnotation("Relational:DefaultConstraintName", "DF_OPJ_RetryCount");
            entity.Property(e => e.UpdatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_OPJ_UpdatedAtUtc");

            entity.HasOne(d => d.Order).WithOne(p => p.OrderProcessingJob)
                .HasForeignKey<OrderProcessingJob>(d => d.OrderId)
                .HasConstraintName("FK_OrderProcessingJobs_Orders");
        });

        modelBuilder.Entity<OrderShippingSnapshot>(entity =>
        {
            entity.HasKey(e => e.OrderId);

            entity.Property(e => e.OrderId).ValueGeneratedNever();
            entity.Property(e => e.AddressLine1)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.AddressLine2).HasMaxLength(256);
            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.CountryCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.DeliveryInstructions).HasMaxLength(500);
            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.PostalCode)
                .IsRequired()
                .HasMaxLength(32);
            entity.Property(e => e.RecipientName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.StateOrRegion).HasMaxLength(128);

            entity.HasOne(d => d.Order).WithOne(p => p.OrderShippingSnapshot)
                .HasForeignKey<OrderShippingSnapshot>(d => d.OrderId)
                .HasConstraintName("FK_OrderShippingSnapshots_Orders");

            entity.HasOne(d => d.SourceCustomerAddress).WithMany(p => p.OrderShippingSnapshots)
                .HasForeignKey(d => d.SourceCustomerAddressId)
                .HasConstraintName("FK_OrderShippingSnapshots_Address");
        });

        modelBuilder.Entity<OrderStatusHistory>(entity =>
        {
            entity.ToTable("OrderStatusHistory");

            entity.HasIndex(e => new { e.OrderId, e.OccurredAtUtc }, "IX_OrderStatusHistory_Order_Time");

            entity.Property(e => e.ActorType)
                .IsRequired()
                .HasMaxLength(32);
            entity.Property(e => e.FromStatus).HasMaxLength(32);
            entity.Property(e => e.OccurredAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_OSH_OccurredAtUtc");
            entity.Property(e => e.Reason).HasMaxLength(500);
            entity.Property(e => e.ToStatus)
                .IsRequired()
                .HasMaxLength(32);

            entity.HasOne(d => d.ActorUser).WithMany(p => p.OrderStatusHistories)
                .HasForeignKey(d => d.ActorUserId)
                .HasConstraintName("FK_OrderStatusHistory_ActorUser");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderStatusHistories)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_OrderStatusHistory_Orders");
        });

        modelBuilder.Entity<PaymentAttempt>(entity =>
        {
            entity.HasIndex(e => e.OrderId, "IX_PaymentAttempts_OrderId");

            entity.HasIndex(e => e.IdempotencyKey, "UQ_PaymentAttempts_IdempotencyKey").IsUnique();

            entity.HasIndex(e => e.OrderId, "UX_PaymentAttempts_OneSucceededPerOrder")
                .IsUnique()
                .HasFilter("([Status]=N'Succeeded')");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PaymentAttempts_CreatedAtUtc");
            entity.Property(e => e.FailureReason).HasMaxLength(500);
            entity.Property(e => e.IdempotencyKey)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.ProviderReference).HasMaxLength(128);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(32);

            entity.HasOne(d => d.Order).WithOne(p => p.PaymentAttempt)
                .HasForeignKey<PaymentAttempt>(d => d.OrderId)
                .HasConstraintName("FK_PaymentAttempts_Orders");
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.HasIndex(e => e.PermissionCode, "UQ_Permissions_Code").IsUnique();

            entity.Property(e => e.Description).HasMaxLength(256);
            entity.Property(e => e.PermissionCode)
                .IsRequired()
                .HasMaxLength(64);
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasIndex(e => e.IsActive, "IX_Products_IsActive");

            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Products_CreatedAtUtc");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Products_IsActive");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ReservedQuantity).HasAnnotation("Relational:DefaultConstraintName", "DF_Products_ReservedQuantity");
            entity.Property(e => e.RowVersion)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.UpdatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Products_UpdatedAtUtc");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.ProductCreatedByUsers)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_Products_CreatedBy");

            entity.HasOne(d => d.UpdatedByUser).WithMany(p => p.ProductUpdatedByUsers)
                .HasForeignKey(d => d.UpdatedByUserId)
                .HasConstraintName("FK_Products_UpdatedBy");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasIndex(e => e.RoleName, "UQ_Roles_Name").IsUnique();

            entity.Property(e => e.Description).HasMaxLength(256);
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(64);

            entity.HasMany(d => d.Permissions).WithMany(p => p.Roles)
                .UsingEntity<Dictionary<string, object>>(
                    "RolePermission",
                    r => r.HasOne<Permission>().WithMany()
                        .HasForeignKey("PermissionId")
                        .HasConstraintName("FK_RolePermissions_Permissions"),
                    l => l.HasOne<Role>().WithMany()
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_RolePermissions_Roles"),
                    j =>
                    {
                        j.HasKey("RoleId", "PermissionId");
                        j.ToTable("RolePermissions");
                    });
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasIndex(e => e.Email, "UQ_Users_Email").IsUnique();

            entity.HasIndex(e => e.Phone, "UQ_Users_Phone_Verified")
                .IsUnique()
                .HasFilter("([Phone] IS NOT NULL AND [IsPhoneVerified]=(1))");

            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Users_CreatedAtUtc");
            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Users_IsActive");
            entity.Property(e => e.IsEmailVerified).HasAnnotation("Relational:DefaultConstraintName", "DF_Users_IsEmailVerified");
            entity.Property(e => e.IsPhoneVerified).HasAnnotation("Relational:DefaultConstraintName", "DF_Users_IsPhoneVerified");
            entity.Property(e => e.LastLoginAtUtc).HasPrecision(3);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.UpdatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Users_UpdatedAtUtc");
        });

        modelBuilder.Entity<UserLoginOtp>(entity =>
        {
            entity.HasKey(e => e.LoginOtpId);

            entity.HasIndex(e => new { e.LoginIdentifier, e.CreatedAtUtc }, "IX_UserLoginOtps_Lookup").IsDescending(false, true);

            entity.HasIndex(e => new { e.UserId, e.CreatedAtUtc }, "IX_UserLoginOtps_UserId").IsDescending(false, true);

            entity.Property(e => e.AttemptCount).HasAnnotation("Relational:DefaultConstraintName", "DF_UserLoginOtps_AttemptCount");
            entity.Property(e => e.ConsumedAtUtc).HasPrecision(3);
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserLoginOtps_CreatedAtUtc");
            entity.Property(e => e.ExpiresAtUtc).HasPrecision(3);
            entity.Property(e => e.LoginIdentifier)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.MaxAttempts)
                .HasDefaultValue(5)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserLoginOtps_MaxAttempts");
            entity.Property(e => e.OtpCodeHash)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.Purpose)
                .IsRequired()
                .HasMaxLength(32)
                .HasDefaultValue("Login")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserLoginOtps_Purpose");

            entity.HasOne(d => d.User).WithMany(p => p.UserLoginOtps)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_UserLoginOtps_Users");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.RoleId });

            entity.Property(e => e.AssignedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRoles_AssignedAtUtc");

            entity.HasOne(d => d.AssignedByUser).WithMany(p => p.UserRoleAssignedByUsers)
                .HasForeignKey(d => d.AssignedByUserId)
                .HasConstraintName("FK_UserRoles_AssignedBy");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoles_Roles");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoleUsers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserRoles_Users");
        });

        modelBuilder.Entity<UserSession>(entity =>
        {
            entity.HasKey(e => e.SessionId);

            entity.HasIndex(e => new { e.UserId, e.RevokedAtUtc, e.ExpiresAtUtc }, "IX_UserSessions_User_Active");

            entity.HasIndex(e => e.RefreshTokenHash, "UQ_UserSessions_RefreshTokenHash").IsUnique();

            entity.Property(e => e.SessionId)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSessions_SessionId");
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSessions_CreatedAtUtc");
            entity.Property(e => e.DeviceName).HasMaxLength(200);
            entity.Property(e => e.ExpiresAtUtc).HasPrecision(3);
            entity.Property(e => e.IpAddress).HasMaxLength(45);
            entity.Property(e => e.LastActivityAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSessions_LastActivityAtUtc");
            entity.Property(e => e.RefreshTokenHash)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.RevokedAtUtc).HasPrecision(3);
            entity.Property(e => e.UserAgent).HasMaxLength(512);

            entity.HasOne(d => d.User).WithMany(p => p.UserSessions)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserSessions_Users");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}