// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderProcessing.Models;

public partial class PaymentAttempt
{
    public long PaymentAttemptId { get; set; }

    public long OrderId { get; set; }

    public int AttemptNo { get; set; }

    public decimal Amount { get; set; }

    public string Status { get; set; }

    public string ProviderReference { get; set; }

    public string IdempotencyKey { get; set; }

    public string FailureReason { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual Order Order { get; set; }
}