// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderProcessing.Models;

public partial class User
{
    public long UserId { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string DisplayName { get; set; }

    public bool IsActive { get; set; }

    public bool IsEmailVerified { get; set; }

    public bool IsPhoneVerified { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public DateTime? LastLoginAtUtc { get; set; }

    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    public virtual Customer Customer { get; set; }

    public virtual ICollection<OrderDomainEvent> OrderDomainEvents { get; set; } = new List<OrderDomainEvent>();

    public virtual ICollection<OrderStatusHistory> OrderStatusHistories { get; set; } = new List<OrderStatusHistory>();

    public virtual ICollection<Product> ProductCreatedByUsers { get; set; } = new List<Product>();

    public virtual ICollection<Product> ProductUpdatedByUsers { get; set; } = new List<Product>();

    public virtual ICollection<UserLoginOtp> UserLoginOtps { get; set; } = new List<UserLoginOtp>();

    public virtual ICollection<UserRole> UserRoleAssignedByUsers { get; set; } = new List<UserRole>();

    public virtual ICollection<UserRole> UserRoleUsers { get; set; } = new List<UserRole>();

    public virtual ICollection<UserSession> UserSessions { get; set; } = new List<UserSession>();
}