// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderProcessing.Models;

public partial class UserRole
{
    public long UserId { get; set; }

    public int RoleId { get; set; }

    public DateTime AssignedAtUtc { get; set; }

    public long? AssignedByUserId { get; set; }

    public virtual User AssignedByUser { get; set; }

    public virtual Role Role { get; set; }

    public virtual User User { get; set; }
}