// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderProcessing.Models;

public partial class UserLoginOtp
{
    public long LoginOtpId { get; set; }

    public long? UserId { get; set; }

    public string LoginIdentifier { get; set; }

    public string OtpCodeHash { get; set; }

    public string Purpose { get; set; }

    public DateTime ExpiresAtUtc { get; set; }

    public DateTime? ConsumedAtUtc { get; set; }

    public int AttemptCount { get; set; }

    public int MaxAttempts { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual User User { get; set; }
}