// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderProcessing.Models;

public partial class UserSession
{
    public Guid SessionId { get; set; }

    public long UserId { get; set; }

    public string RefreshTokenHash { get; set; }

    public string DeviceName { get; set; }

    public string UserAgent { get; set; }

    public string IpAddress { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime ExpiresAtUtc { get; set; }

    public DateTime? RevokedAtUtc { get; set; }

    public DateTime LastActivityAtUtc { get; set; }

    public virtual User User { get; set; }
}